[package]
name = "raylib-framework-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
raylib = "5.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
